-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}

-- | Contains the default configuration
module MockServer.Configuration where

import qualified Data.Text
import qualified GHC.Types 
import qualified MockServer.Common

-- | The default url specified by the OpenAPI specification
-- 
-- @http://localhost:1080/@
defaultURL = Data.Text.pack "http://localhost:1080/"
-- | The default application name used in the @User-Agent@ header which is based on the @info.title@ field of the specification
-- 
-- @MockServer API@
defaultApplicationName = Data.Text.pack "MockServer API"
-- | The default configuration containing the 'defaultURL' and no authorization
defaultConfiguration = MockServer.Common.Configuration defaultURL MockServer.Common.anonymousSecurityScheme GHC.Types.True defaultApplicationName
