-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module MockServer.TypeAlias where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common


-- | Defines an alias for the schema located at @components.schemas.RawStringResponseBody@ in the specification.
-- 
-- string response body
type RawStringResponseBody = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.RawStringBodyMatcher@ in the specification.
-- 
-- substring body matcher
type RawStringBodyMatcher = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.RawJsonResponseBody@ in the specification.
-- 
-- json response body
type RawJsonResponseBody = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.RawJsonBodyMatcher@ in the specification.
-- 
-- json matching fields body matcher
type RawJsonBodyMatcher = Data.Aeson.Types.Internal.Object
