-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema BinaryBodyResponse
module MockServer.Types.BinaryBodyResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.BinaryBodyResponse@ in the specification.
-- 
-- binary response body
data BinaryBodyResponse = BinaryBodyResponse {
  -- | base64Bytes
  binaryBodyResponseBase64Bytes :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | contentType
  , binaryBodyResponseContentType :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | not
  , binaryBodyResponseNot :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | type
  , binaryBodyResponseType :: (GHC.Maybe.Maybe BinaryBodyResponseType)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON BinaryBodyResponse
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("base64Bytes" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseBase64Bytes obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("contentType" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseContentType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseType obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("base64Bytes" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseBase64Bytes obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("contentType" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseContentType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (binaryBodyResponseType obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON BinaryBodyResponse
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "BinaryBodyResponse" (\obj -> (((GHC.Base.pure BinaryBodyResponse GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "base64Bytes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "contentType")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "not")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))
-- | Create a new 'BinaryBodyResponse' with all required fields.
mkBinaryBodyResponse :: BinaryBodyResponse
mkBinaryBodyResponse = BinaryBodyResponse{binaryBodyResponseBase64Bytes = GHC.Maybe.Nothing,
                                          binaryBodyResponseContentType = GHC.Maybe.Nothing,
                                          binaryBodyResponseNot = GHC.Maybe.Nothing,
                                          binaryBodyResponseType = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.BinaryBodyResponse.properties.type@ in the specification.
-- 
-- 
data BinaryBodyResponseType =
   BinaryBodyResponseTypeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | BinaryBodyResponseTypeTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | BinaryBodyResponseTypeEnumBINARY -- ^ Represents the JSON value @"BINARY"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON BinaryBodyResponseType
    where toJSON (BinaryBodyResponseTypeOther val) = val
          toJSON (BinaryBodyResponseTypeTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (BinaryBodyResponseTypeEnumBINARY) = "BINARY"
instance Data.Aeson.Types.FromJSON.FromJSON BinaryBodyResponseType
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "BINARY" -> BinaryBodyResponseTypeEnumBINARY
                                            | GHC.Base.otherwise -> BinaryBodyResponseTypeOther val)
