-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema HttpOverrideForwardedRequest
module MockServer.Types.HttpOverrideForwardedRequest where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias
import {-# SOURCE #-} MockServer.Types.Delay
import {-# SOURCE #-} MockServer.Types.HttpRequest
import {-# SOURCE #-} MockServer.Types.HttpResponse
import {-# SOURCE #-} MockServer.Types.KeyToMultiValue
import {-# SOURCE #-} MockServer.Types.KeyToValue

-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1 = HttpOverrideForwardedRequestOneOf1 {
  -- | delay: response delay
  httpOverrideForwardedRequestOneOf1Delay :: (GHC.Maybe.Maybe Delay)
  -- | requestModifier
  , httpOverrideForwardedRequestOneOf1RequestModifier :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1RequestModifier)
  -- | requestOverride
  , httpOverrideForwardedRequestOneOf1RequestOverride :: (GHC.Maybe.Maybe HttpRequest)
  -- | responseModifier
  , httpOverrideForwardedRequestOneOf1ResponseModifier :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1ResponseModifier)
  -- | responseOverride
  , httpOverrideForwardedRequestOneOf1ResponseOverride :: (GHC.Maybe.Maybe HttpResponse)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("delay" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1Delay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("requestModifier" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifier obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("requestOverride" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestOverride obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("responseModifier" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifier obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("responseOverride" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseOverride obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("delay" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1Delay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("requestModifier" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifier obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("requestOverride" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestOverride obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("responseModifier" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifier obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("responseOverride" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseOverride obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1" (\obj -> ((((GHC.Base.pure HttpOverrideForwardedRequestOneOf1 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "delay")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "requestModifier")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "requestOverride")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "responseModifier")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "responseOverride"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1' with all required fields.
mkHttpOverrideForwardedRequestOneOf1 :: HttpOverrideForwardedRequestOneOf1
mkHttpOverrideForwardedRequestOneOf1 = HttpOverrideForwardedRequestOneOf1{httpOverrideForwardedRequestOneOf1Delay = GHC.Maybe.Nothing,
                                                                          httpOverrideForwardedRequestOneOf1RequestModifier = GHC.Maybe.Nothing,
                                                                          httpOverrideForwardedRequestOneOf1RequestOverride = GHC.Maybe.Nothing,
                                                                          httpOverrideForwardedRequestOneOf1ResponseModifier = GHC.Maybe.Nothing,
                                                                          httpOverrideForwardedRequestOneOf1ResponseOverride = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.requestModifier@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1RequestModifier = HttpOverrideForwardedRequestOneOf1RequestModifier {
  -- | cookies
  httpOverrideForwardedRequestOneOf1RequestModifierCookies :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1RequestModifierCookies)
  -- | headers
  , httpOverrideForwardedRequestOneOf1RequestModifierHeaders :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1RequestModifierHeaders)
  -- | path
  , httpOverrideForwardedRequestOneOf1RequestModifierPath :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1RequestModifierPath)
  -- | queryStringParameters
  , httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1RequestModifier
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("cookies" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookies obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("headers" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeaders obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("path" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierPath obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryStringParameters" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("cookies" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookies obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("headers" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeaders obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("path" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierPath obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryStringParameters" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1RequestModifier
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1RequestModifier" (\obj -> (((GHC.Base.pure HttpOverrideForwardedRequestOneOf1RequestModifier GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "cookies")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "headers")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "path")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryStringParameters"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1RequestModifier' with all required fields.
mkHttpOverrideForwardedRequestOneOf1RequestModifier :: HttpOverrideForwardedRequestOneOf1RequestModifier
mkHttpOverrideForwardedRequestOneOf1RequestModifier = HttpOverrideForwardedRequestOneOf1RequestModifier{httpOverrideForwardedRequestOneOf1RequestModifierCookies = GHC.Maybe.Nothing,
                                                                                                        httpOverrideForwardedRequestOneOf1RequestModifierHeaders = GHC.Maybe.Nothing,
                                                                                                        httpOverrideForwardedRequestOneOf1RequestModifierPath = GHC.Maybe.Nothing,
                                                                                                        httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.requestModifier.properties.cookies@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1RequestModifierCookies = HttpOverrideForwardedRequestOneOf1RequestModifierCookies {
  -- | add
  httpOverrideForwardedRequestOneOf1RequestModifierCookiesAdd :: (GHC.Maybe.Maybe KeyToValue)
  -- | remove
  , httpOverrideForwardedRequestOneOf1RequestModifierCookiesRemove :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | replace
  , httpOverrideForwardedRequestOneOf1RequestModifierCookiesReplace :: (GHC.Maybe.Maybe KeyToValue)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierCookies
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookiesAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookiesRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookiesReplace obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookiesAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookiesRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierCookiesReplace obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierCookies
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1RequestModifierCookies" (\obj -> ((GHC.Base.pure HttpOverrideForwardedRequestOneOf1RequestModifierCookies GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "add")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "replace"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1RequestModifierCookies' with all required fields.
mkHttpOverrideForwardedRequestOneOf1RequestModifierCookies :: HttpOverrideForwardedRequestOneOf1RequestModifierCookies
mkHttpOverrideForwardedRequestOneOf1RequestModifierCookies = HttpOverrideForwardedRequestOneOf1RequestModifierCookies{httpOverrideForwardedRequestOneOf1RequestModifierCookiesAdd = GHC.Maybe.Nothing,
                                                                                                                      httpOverrideForwardedRequestOneOf1RequestModifierCookiesRemove = GHC.Maybe.Nothing,
                                                                                                                      httpOverrideForwardedRequestOneOf1RequestModifierCookiesReplace = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.requestModifier.properties.headers@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1RequestModifierHeaders = HttpOverrideForwardedRequestOneOf1RequestModifierHeaders {
  -- | add
  httpOverrideForwardedRequestOneOf1RequestModifierHeadersAdd :: (GHC.Maybe.Maybe KeyToMultiValue)
  -- | remove
  , httpOverrideForwardedRequestOneOf1RequestModifierHeadersRemove :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | replace
  , httpOverrideForwardedRequestOneOf1RequestModifierHeadersReplace :: (GHC.Maybe.Maybe KeyToMultiValue)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeadersAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeadersRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeadersReplace obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeadersAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeadersRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierHeadersReplace obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1RequestModifierHeaders" (\obj -> ((GHC.Base.pure HttpOverrideForwardedRequestOneOf1RequestModifierHeaders GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "add")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "replace"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1RequestModifierHeaders' with all required fields.
mkHttpOverrideForwardedRequestOneOf1RequestModifierHeaders :: HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
mkHttpOverrideForwardedRequestOneOf1RequestModifierHeaders = HttpOverrideForwardedRequestOneOf1RequestModifierHeaders{httpOverrideForwardedRequestOneOf1RequestModifierHeadersAdd = GHC.Maybe.Nothing,
                                                                                                                      httpOverrideForwardedRequestOneOf1RequestModifierHeadersRemove = GHC.Maybe.Nothing,
                                                                                                                      httpOverrideForwardedRequestOneOf1RequestModifierHeadersReplace = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.requestModifier.properties.path@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1RequestModifierPath = HttpOverrideForwardedRequestOneOf1RequestModifierPath {
  -- | regex
  httpOverrideForwardedRequestOneOf1RequestModifierPathRegex :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | substitution
  , httpOverrideForwardedRequestOneOf1RequestModifierPathSubstitution :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierPath
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("regex" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierPathRegex obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("substitution" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierPathSubstitution obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("regex" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierPathRegex obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("substitution" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierPathSubstitution obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierPath
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1RequestModifierPath" (\obj -> (GHC.Base.pure HttpOverrideForwardedRequestOneOf1RequestModifierPath GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "regex")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "substitution"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1RequestModifierPath' with all required fields.
mkHttpOverrideForwardedRequestOneOf1RequestModifierPath :: HttpOverrideForwardedRequestOneOf1RequestModifierPath
mkHttpOverrideForwardedRequestOneOf1RequestModifierPath = HttpOverrideForwardedRequestOneOf1RequestModifierPath{httpOverrideForwardedRequestOneOf1RequestModifierPathRegex = GHC.Maybe.Nothing,
                                                                                                                httpOverrideForwardedRequestOneOf1RequestModifierPathSubstitution = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.requestModifier.properties.queryStringParameters@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters = HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters {
  -- | add
  httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersAdd :: (GHC.Maybe.Maybe KeyToMultiValue)
  -- | remove
  , httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersRemove :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | replace
  , httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersReplace :: (GHC.Maybe.Maybe KeyToMultiValue)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersReplace obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersReplace obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters" (\obj -> ((GHC.Base.pure HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "add")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "replace"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters' with all required fields.
mkHttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters :: HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
mkHttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters = HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters{httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersAdd = GHC.Maybe.Nothing,
                                                                                                                                                  httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersRemove = GHC.Maybe.Nothing,
                                                                                                                                                  httpOverrideForwardedRequestOneOf1RequestModifierQueryStringParametersReplace = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.responseModifier@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1ResponseModifier = HttpOverrideForwardedRequestOneOf1ResponseModifier {
  -- | cookies
  httpOverrideForwardedRequestOneOf1ResponseModifierCookies :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1ResponseModifierCookies)
  -- | headers
  , httpOverrideForwardedRequestOneOf1ResponseModifierHeaders :: (GHC.Maybe.Maybe HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1ResponseModifier
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("cookies" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookies obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("headers" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeaders obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("cookies" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookies obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("headers" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeaders obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1ResponseModifier
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1ResponseModifier" (\obj -> (GHC.Base.pure HttpOverrideForwardedRequestOneOf1ResponseModifier GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "cookies")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "headers"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1ResponseModifier' with all required fields.
mkHttpOverrideForwardedRequestOneOf1ResponseModifier :: HttpOverrideForwardedRequestOneOf1ResponseModifier
mkHttpOverrideForwardedRequestOneOf1ResponseModifier = HttpOverrideForwardedRequestOneOf1ResponseModifier{httpOverrideForwardedRequestOneOf1ResponseModifierCookies = GHC.Maybe.Nothing,
                                                                                                          httpOverrideForwardedRequestOneOf1ResponseModifierHeaders = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.responseModifier.properties.cookies@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1ResponseModifierCookies = HttpOverrideForwardedRequestOneOf1ResponseModifierCookies {
  -- | add
  httpOverrideForwardedRequestOneOf1ResponseModifierCookiesAdd :: (GHC.Maybe.Maybe KeyToValue)
  -- | remove
  , httpOverrideForwardedRequestOneOf1ResponseModifierCookiesRemove :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | replace
  , httpOverrideForwardedRequestOneOf1ResponseModifierCookiesReplace :: (GHC.Maybe.Maybe KeyToValue)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookiesAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookiesRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookiesReplace obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookiesAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookiesRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierCookiesReplace obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1ResponseModifierCookies" (\obj -> ((GHC.Base.pure HttpOverrideForwardedRequestOneOf1ResponseModifierCookies GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "add")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "replace"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1ResponseModifierCookies' with all required fields.
mkHttpOverrideForwardedRequestOneOf1ResponseModifierCookies :: HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
mkHttpOverrideForwardedRequestOneOf1ResponseModifierCookies = HttpOverrideForwardedRequestOneOf1ResponseModifierCookies{httpOverrideForwardedRequestOneOf1ResponseModifierCookiesAdd = GHC.Maybe.Nothing,
                                                                                                                        httpOverrideForwardedRequestOneOf1ResponseModifierCookiesRemove = GHC.Maybe.Nothing,
                                                                                                                        httpOverrideForwardedRequestOneOf1ResponseModifierCookiesReplace = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf.properties.responseModifier.properties.headers@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders = HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders {
  -- | add
  httpOverrideForwardedRequestOneOf1ResponseModifierHeadersAdd :: (GHC.Maybe.Maybe KeyToMultiValue)
  -- | remove
  , httpOverrideForwardedRequestOneOf1ResponseModifierHeadersRemove :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | replace
  , httpOverrideForwardedRequestOneOf1ResponseModifierHeadersReplace :: (GHC.Maybe.Maybe KeyToMultiValue)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeadersAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeadersRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeadersReplace obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("add" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeadersAdd obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("remove" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeadersRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("replace" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf1ResponseModifierHeadersReplace obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders" (\obj -> ((GHC.Base.pure HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "add")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "replace"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders' with all required fields.
mkHttpOverrideForwardedRequestOneOf1ResponseModifierHeaders :: HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
mkHttpOverrideForwardedRequestOneOf1ResponseModifierHeaders = HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders{httpOverrideForwardedRequestOneOf1ResponseModifierHeadersAdd = GHC.Maybe.Nothing,
                                                                                                                        httpOverrideForwardedRequestOneOf1ResponseModifierHeadersRemove = GHC.Maybe.Nothing,
                                                                                                                        httpOverrideForwardedRequestOneOf1ResponseModifierHeadersReplace = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestOneOf2 = HttpOverrideForwardedRequestOneOf2 {
  -- | delay: response delay
  httpOverrideForwardedRequestOneOf2Delay :: (GHC.Maybe.Maybe Delay)
  -- | httpRequest
  , httpOverrideForwardedRequestOneOf2HttpRequest :: (GHC.Maybe.Maybe HttpRequest)
  -- | httpResponse
  , httpOverrideForwardedRequestOneOf2HttpResponse :: (GHC.Maybe.Maybe HttpResponse)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestOneOf2
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("delay" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf2Delay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpRequest" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf2HttpRequest obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpResponse" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf2HttpResponse obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("delay" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf2Delay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpRequest" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf2HttpRequest obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpResponse" Data.Aeson.Types.ToJSON..=)) (httpOverrideForwardedRequestOneOf2HttpResponse obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestOneOf2
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpOverrideForwardedRequestOneOf2" (\obj -> ((GHC.Base.pure HttpOverrideForwardedRequestOneOf2 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "delay")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "httpRequest")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "httpResponse"))
-- | Create a new 'HttpOverrideForwardedRequestOneOf2' with all required fields.
mkHttpOverrideForwardedRequestOneOf2 :: HttpOverrideForwardedRequestOneOf2
mkHttpOverrideForwardedRequestOneOf2 = HttpOverrideForwardedRequestOneOf2{httpOverrideForwardedRequestOneOf2Delay = GHC.Maybe.Nothing,
                                                                          httpOverrideForwardedRequestOneOf2HttpRequest = GHC.Maybe.Nothing,
                                                                          httpOverrideForwardedRequestOneOf2HttpResponse = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf@ in the specification.
-- 
-- 
data HttpOverrideForwardedRequestVariants =
   HttpOverrideForwardedRequestHttpOverrideForwardedRequestOneOf1 HttpOverrideForwardedRequestOneOf1
  | HttpOverrideForwardedRequestHttpOverrideForwardedRequestOneOf2 HttpOverrideForwardedRequestOneOf2
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpOverrideForwardedRequestVariants
    where toJSON (HttpOverrideForwardedRequestHttpOverrideForwardedRequestOneOf1 a) = Data.Aeson.Types.ToJSON.toJSON a
          toJSON (HttpOverrideForwardedRequestHttpOverrideForwardedRequestOneOf2 a) = Data.Aeson.Types.ToJSON.toJSON a
instance Data.Aeson.Types.FromJSON.FromJSON HttpOverrideForwardedRequestVariants
    where parseJSON val = case (HttpOverrideForwardedRequestHttpOverrideForwardedRequestOneOf1 Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((HttpOverrideForwardedRequestHttpOverrideForwardedRequestOneOf2 Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                              Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
                              Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a
-- | Defines an alias for the schema located at @components.schemas.HttpOverrideForwardedRequest.oneOf@ in the specification.
-- 
-- 
type HttpOverrideForwardedRequest = HttpOverrideForwardedRequestVariants
