-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema HttpClassCallback
module MockServer.Types.HttpClassCallback where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias
import {-# SOURCE #-} MockServer.Types.Delay

-- | Defines the object schema located at @components.schemas.HttpClassCallback@ in the specification.
-- 
-- 
data HttpClassCallback = HttpClassCallback {
  -- | callbackClass
  httpClassCallbackCallbackClass :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | delay: response delay
  , httpClassCallbackDelay :: (GHC.Maybe.Maybe Delay)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON HttpClassCallback
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("callbackClass" Data.Aeson.Types.ToJSON..=)) (httpClassCallbackCallbackClass obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("delay" Data.Aeson.Types.ToJSON..=)) (httpClassCallbackDelay obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("callbackClass" Data.Aeson.Types.ToJSON..=)) (httpClassCallbackCallbackClass obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("delay" Data.Aeson.Types.ToJSON..=)) (httpClassCallbackDelay obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON HttpClassCallback
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "HttpClassCallback" (\obj -> (GHC.Base.pure HttpClassCallback GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "callbackClass")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "delay"))
-- | Create a new 'HttpClassCallback' with all required fields.
mkHttpClassCallback :: HttpClassCallback
mkHttpClassCallback = HttpClassCallback{httpClassCallbackCallbackClass = GHC.Maybe.Nothing,
                                        httpClassCallbackDelay = GHC.Maybe.Nothing}
