module MockServer.Types.HttpOverrideForwardedRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified MockServer.Common
data HttpOverrideForwardedRequestOneOf1
instance Show HttpOverrideForwardedRequestOneOf1
instance Eq HttpOverrideForwardedRequestOneOf1
instance FromJSON HttpOverrideForwardedRequestOneOf1
instance ToJSON HttpOverrideForwardedRequestOneOf1
data HttpOverrideForwardedRequestOneOf1RequestModifier
instance Show HttpOverrideForwardedRequestOneOf1RequestModifier
instance Eq HttpOverrideForwardedRequestOneOf1RequestModifier
instance FromJSON HttpOverrideForwardedRequestOneOf1RequestModifier
instance ToJSON HttpOverrideForwardedRequestOneOf1RequestModifier
data HttpOverrideForwardedRequestOneOf1RequestModifierCookies
instance Show HttpOverrideForwardedRequestOneOf1RequestModifierCookies
instance Eq HttpOverrideForwardedRequestOneOf1RequestModifierCookies
instance FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierCookies
instance ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierCookies
data HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
instance Show HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
instance Eq HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
instance FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
instance ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierHeaders
data HttpOverrideForwardedRequestOneOf1RequestModifierPath
instance Show HttpOverrideForwardedRequestOneOf1RequestModifierPath
instance Eq HttpOverrideForwardedRequestOneOf1RequestModifierPath
instance FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierPath
instance ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierPath
data HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
instance Show HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
instance Eq HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
instance FromJSON HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
instance ToJSON HttpOverrideForwardedRequestOneOf1RequestModifierQueryStringParameters
data HttpOverrideForwardedRequestOneOf1ResponseModifier
instance Show HttpOverrideForwardedRequestOneOf1ResponseModifier
instance Eq HttpOverrideForwardedRequestOneOf1ResponseModifier
instance FromJSON HttpOverrideForwardedRequestOneOf1ResponseModifier
instance ToJSON HttpOverrideForwardedRequestOneOf1ResponseModifier
data HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
instance Show HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
instance Eq HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
instance FromJSON HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
instance ToJSON HttpOverrideForwardedRequestOneOf1ResponseModifierCookies
data HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
instance Show HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
instance Eq HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
instance FromJSON HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
instance ToJSON HttpOverrideForwardedRequestOneOf1ResponseModifierHeaders
data HttpOverrideForwardedRequestOneOf2
instance Show HttpOverrideForwardedRequestOneOf2
instance Eq HttpOverrideForwardedRequestOneOf2
instance FromJSON HttpOverrideForwardedRequestOneOf2
instance ToJSON HttpOverrideForwardedRequestOneOf2
data HttpOverrideForwardedRequestVariants
instance Show HttpOverrideForwardedRequestVariants
instance Eq HttpOverrideForwardedRequestVariants
instance FromJSON HttpOverrideForwardedRequestVariants
instance ToJSON HttpOverrideForwardedRequestVariants
type HttpOverrideForwardedRequest = HttpOverrideForwardedRequestVariants
