-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema OpenAPIExpectations
module MockServer.Types.OpenAPIExpectations where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias
import {-# SOURCE #-} MockServer.Types.OpenAPIExpectation

-- | Defines the oneOf schema located at @components.schemas.OpenAPIExpectations.oneOf@ in the specification.
-- 
-- 
data OpenAPIExpectationsVariants =
   OpenAPIExpectationsOpenAPIExpectation OpenAPIExpectation
  | OpenAPIExpectationsListTOpenAPIExpectation ([OpenAPIExpectation])
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON OpenAPIExpectationsVariants
    where toJSON (OpenAPIExpectationsOpenAPIExpectation a) = Data.Aeson.Types.ToJSON.toJSON a
          toJSON (OpenAPIExpectationsListTOpenAPIExpectation a) = Data.Aeson.Types.ToJSON.toJSON a
instance Data.Aeson.Types.FromJSON.FromJSON OpenAPIExpectationsVariants
    where parseJSON val = case (OpenAPIExpectationsOpenAPIExpectation Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((OpenAPIExpectationsListTOpenAPIExpectation Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                              Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
                              Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a
-- | Defines an alias for the schema located at @components.schemas.OpenAPIExpectations.oneOf@ in the specification.
-- 
-- 
type OpenAPIExpectations = OpenAPIExpectationsVariants
