-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema OpenAPIDefinition
module MockServer.Types.OpenAPIDefinition where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.OpenAPIDefinition@ in the specification.
-- 
-- 
data OpenAPIDefinition = OpenAPIDefinition {
  -- | operationId
  openAPIDefinitionOperationId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | specUrlOrPayload
  , openAPIDefinitionSpecUrlOrPayload :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON OpenAPIDefinition
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("operationId" Data.Aeson.Types.ToJSON..=)) (openAPIDefinitionOperationId obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("specUrlOrPayload" Data.Aeson.Types.ToJSON..=)) (openAPIDefinitionSpecUrlOrPayload obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("operationId" Data.Aeson.Types.ToJSON..=)) (openAPIDefinitionOperationId obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("specUrlOrPayload" Data.Aeson.Types.ToJSON..=)) (openAPIDefinitionSpecUrlOrPayload obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON OpenAPIDefinition
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "OpenAPIDefinition" (\obj -> (GHC.Base.pure OpenAPIDefinition GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "operationId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "specUrlOrPayload"))
-- | Create a new 'OpenAPIDefinition' with all required fields.
mkOpenAPIDefinition :: OpenAPIDefinition
mkOpenAPIDefinition = OpenAPIDefinition{openAPIDefinitionOperationId = GHC.Maybe.Nothing,
                                        openAPIDefinitionSpecUrlOrPayload = GHC.Maybe.Nothing}
