-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Protocol
module MockServer.Types.Protocol where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the enum schema located at @components.schemas.Protocol@ in the specification.
-- 
-- protocol matcher
data Protocol =
   ProtocolOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | ProtocolTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | ProtocolEnumHTTP_1_1 -- ^ Represents the JSON value @"HTTP_1_1"@
  | ProtocolEnumHTTP_2 -- ^ Represents the JSON value @"HTTP_2"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Protocol
    where toJSON (ProtocolOther val) = val
          toJSON (ProtocolTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (ProtocolEnumHTTP_1_1) = "HTTP_1_1"
          toJSON (ProtocolEnumHTTP_2) = "HTTP_2"
instance Data.Aeson.Types.FromJSON.FromJSON Protocol
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "HTTP_1_1" -> ProtocolEnumHTTP_1_1
                                            | val GHC.Classes.== "HTTP_2" -> ProtocolEnumHTTP_2
                                            | GHC.Base.otherwise -> ProtocolOther val)
