-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema RegexBodyMatcher
module MockServer.Types.RegexBodyMatcher where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.RegexBodyMatcher@ in the specification.
-- 
-- regex body matcher
data RegexBodyMatcher = RegexBodyMatcher {
  -- | not
  regexBodyMatcherNot :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | regex
  , regexBodyMatcherRegex :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | type
  , regexBodyMatcherType :: (GHC.Maybe.Maybe RegexBodyMatcherType)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON RegexBodyMatcher
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (regexBodyMatcherNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("regex" Data.Aeson.Types.ToJSON..=)) (regexBodyMatcherRegex obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (regexBodyMatcherType obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (regexBodyMatcherNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("regex" Data.Aeson.Types.ToJSON..=)) (regexBodyMatcherRegex obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (regexBodyMatcherType obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON RegexBodyMatcher
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "RegexBodyMatcher" (\obj -> ((GHC.Base.pure RegexBodyMatcher GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "not")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "regex")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))
-- | Create a new 'RegexBodyMatcher' with all required fields.
mkRegexBodyMatcher :: RegexBodyMatcher
mkRegexBodyMatcher = RegexBodyMatcher{regexBodyMatcherNot = GHC.Maybe.Nothing,
                                      regexBodyMatcherRegex = GHC.Maybe.Nothing,
                                      regexBodyMatcherType = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.RegexBodyMatcher.properties.type@ in the specification.
-- 
-- 
data RegexBodyMatcherType =
   RegexBodyMatcherTypeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | RegexBodyMatcherTypeTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | RegexBodyMatcherTypeEnumREGEX -- ^ Represents the JSON value @"REGEX"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON RegexBodyMatcherType
    where toJSON (RegexBodyMatcherTypeOther val) = val
          toJSON (RegexBodyMatcherTypeTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (RegexBodyMatcherTypeEnumREGEX) = "REGEX"
instance Data.Aeson.Types.FromJSON.FromJSON RegexBodyMatcherType
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "REGEX" -> RegexBodyMatcherTypeEnumREGEX
                                            | GHC.Base.otherwise -> RegexBodyMatcherTypeOther val)
