-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema SocketAddress
module MockServer.Types.SocketAddress where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.SocketAddress@ in the specification.
-- 
-- 
data SocketAddress = SocketAddress {
  -- | host
  socketAddressHost :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | port
  , socketAddressPort :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | scheme
  , socketAddressScheme :: (GHC.Maybe.Maybe SocketAddressScheme)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SocketAddress
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("host" Data.Aeson.Types.ToJSON..=)) (socketAddressHost obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("port" Data.Aeson.Types.ToJSON..=)) (socketAddressPort obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("scheme" Data.Aeson.Types.ToJSON..=)) (socketAddressScheme obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("host" Data.Aeson.Types.ToJSON..=)) (socketAddressHost obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("port" Data.Aeson.Types.ToJSON..=)) (socketAddressPort obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("scheme" Data.Aeson.Types.ToJSON..=)) (socketAddressScheme obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON SocketAddress
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "SocketAddress" (\obj -> ((GHC.Base.pure SocketAddress GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "host")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "port")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "scheme"))
-- | Create a new 'SocketAddress' with all required fields.
mkSocketAddress :: SocketAddress
mkSocketAddress = SocketAddress{socketAddressHost = GHC.Maybe.Nothing,
                                socketAddressPort = GHC.Maybe.Nothing,
                                socketAddressScheme = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.SocketAddress.properties.scheme@ in the specification.
-- 
-- 
data SocketAddressScheme =
   SocketAddressSchemeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | SocketAddressSchemeTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | SocketAddressSchemeEnumHTTP -- ^ Represents the JSON value @"HTTP"@
  | SocketAddressSchemeEnumHTTPS -- ^ Represents the JSON value @"HTTPS"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON SocketAddressScheme
    where toJSON (SocketAddressSchemeOther val) = val
          toJSON (SocketAddressSchemeTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (SocketAddressSchemeEnumHTTP) = "HTTP"
          toJSON (SocketAddressSchemeEnumHTTPS) = "HTTPS"
instance Data.Aeson.Types.FromJSON.FromJSON SocketAddressScheme
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "HTTP" -> SocketAddressSchemeEnumHTTP
                                            | val GHC.Classes.== "HTTPS" -> SocketAddressSchemeEnumHTTPS
                                            | GHC.Base.otherwise -> SocketAddressSchemeOther val)
