-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema TimeToLive
module MockServer.Types.TimeToLive where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.TimeToLive@ in the specification.
-- 
-- 
data TimeToLive = TimeToLive {
  -- | timeToLive
  timeToLiveTimeToLive :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | timeUnit
  , timeToLiveTimeUnit :: (GHC.Maybe.Maybe TimeToLiveTimeUnit)
  -- | unlimited
  , timeToLiveUnlimited :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON TimeToLive
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("timeToLive" Data.Aeson.Types.ToJSON..=)) (timeToLiveTimeToLive obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("timeUnit" Data.Aeson.Types.ToJSON..=)) (timeToLiveTimeUnit obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unlimited" Data.Aeson.Types.ToJSON..=)) (timeToLiveUnlimited obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("timeToLive" Data.Aeson.Types.ToJSON..=)) (timeToLiveTimeToLive obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("timeUnit" Data.Aeson.Types.ToJSON..=)) (timeToLiveTimeUnit obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unlimited" Data.Aeson.Types.ToJSON..=)) (timeToLiveUnlimited obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON TimeToLive
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "TimeToLive" (\obj -> ((GHC.Base.pure TimeToLive GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "timeToLive")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "timeUnit")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "unlimited"))
-- | Create a new 'TimeToLive' with all required fields.
mkTimeToLive :: TimeToLive
mkTimeToLive = TimeToLive{timeToLiveTimeToLive = GHC.Maybe.Nothing,
                          timeToLiveTimeUnit = GHC.Maybe.Nothing,
                          timeToLiveUnlimited = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.TimeToLive.properties.timeUnit@ in the specification.
-- 
-- 
data TimeToLiveTimeUnit =
   TimeToLiveTimeUnitOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | TimeToLiveTimeUnitTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | TimeToLiveTimeUnitEnumDAYS -- ^ Represents the JSON value @"DAYS"@
  | TimeToLiveTimeUnitEnumHOURS -- ^ Represents the JSON value @"HOURS"@
  | TimeToLiveTimeUnitEnumMINUTES -- ^ Represents the JSON value @"MINUTES"@
  | TimeToLiveTimeUnitEnumSECONDS -- ^ Represents the JSON value @"SECONDS"@
  | TimeToLiveTimeUnitEnumMILLISECONDS -- ^ Represents the JSON value @"MILLISECONDS"@
  | TimeToLiveTimeUnitEnumMICROSECONDS -- ^ Represents the JSON value @"MICROSECONDS"@
  | TimeToLiveTimeUnitEnumNANOSECONDS -- ^ Represents the JSON value @"NANOSECONDS"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON TimeToLiveTimeUnit
    where toJSON (TimeToLiveTimeUnitOther val) = val
          toJSON (TimeToLiveTimeUnitTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (TimeToLiveTimeUnitEnumDAYS) = "DAYS"
          toJSON (TimeToLiveTimeUnitEnumHOURS) = "HOURS"
          toJSON (TimeToLiveTimeUnitEnumMINUTES) = "MINUTES"
          toJSON (TimeToLiveTimeUnitEnumSECONDS) = "SECONDS"
          toJSON (TimeToLiveTimeUnitEnumMILLISECONDS) = "MILLISECONDS"
          toJSON (TimeToLiveTimeUnitEnumMICROSECONDS) = "MICROSECONDS"
          toJSON (TimeToLiveTimeUnitEnumNANOSECONDS) = "NANOSECONDS"
instance Data.Aeson.Types.FromJSON.FromJSON TimeToLiveTimeUnit
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "DAYS" -> TimeToLiveTimeUnitEnumDAYS
                                            | val GHC.Classes.== "HOURS" -> TimeToLiveTimeUnitEnumHOURS
                                            | val GHC.Classes.== "MINUTES" -> TimeToLiveTimeUnitEnumMINUTES
                                            | val GHC.Classes.== "SECONDS" -> TimeToLiveTimeUnitEnumSECONDS
                                            | val GHC.Classes.== "MILLISECONDS" -> TimeToLiveTimeUnitEnumMILLISECONDS
                                            | val GHC.Classes.== "MICROSECONDS" -> TimeToLiveTimeUnitEnumMICROSECONDS
                                            | val GHC.Classes.== "NANOSECONDS" -> TimeToLiveTimeUnitEnumNANOSECONDS
                                            | GHC.Base.otherwise -> TimeToLiveTimeUnitOther val)
