-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema VerificationSequence
module MockServer.Types.VerificationSequence where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias
import {-# SOURCE #-} MockServer.Types.ExpectationId
import {-# SOURCE #-} MockServer.Types.RequestDefinition

-- | Defines the object schema located at @components.schemas.VerificationSequence@ in the specification.
-- 
-- verification sequence
data VerificationSequence = VerificationSequence {
  -- | expectationIds
  verificationSequenceExpectationIds :: (GHC.Maybe.Maybe ([ExpectationId]))
  -- | httpRequests
  , verificationSequenceHttpRequests :: (GHC.Maybe.Maybe ([RequestDefinition]))
  -- | maximumNumberOfRequestToReturnInVerificationFailure
  , verificationSequenceMaximumNumberOfRequestToReturnInVerificationFailure :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON VerificationSequence
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("expectationIds" Data.Aeson.Types.ToJSON..=)) (verificationSequenceExpectationIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpRequests" Data.Aeson.Types.ToJSON..=)) (verificationSequenceHttpRequests obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("maximumNumberOfRequestToReturnInVerificationFailure" Data.Aeson.Types.ToJSON..=)) (verificationSequenceMaximumNumberOfRequestToReturnInVerificationFailure obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("expectationIds" Data.Aeson.Types.ToJSON..=)) (verificationSequenceExpectationIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpRequests" Data.Aeson.Types.ToJSON..=)) (verificationSequenceHttpRequests obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("maximumNumberOfRequestToReturnInVerificationFailure" Data.Aeson.Types.ToJSON..=)) (verificationSequenceMaximumNumberOfRequestToReturnInVerificationFailure obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON VerificationSequence
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "VerificationSequence" (\obj -> ((GHC.Base.pure VerificationSequence GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "expectationIds")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "httpRequests")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "maximumNumberOfRequestToReturnInVerificationFailure"))
-- | Create a new 'VerificationSequence' with all required fields.
mkVerificationSequence :: VerificationSequence
mkVerificationSequence = VerificationSequence{verificationSequenceExpectationIds = GHC.Maybe.Nothing,
                                              verificationSequenceHttpRequests = GHC.Maybe.Nothing,
                                              verificationSequenceMaximumNumberOfRequestToReturnInVerificationFailure = GHC.Maybe.Nothing}
