-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Verification
module MockServer.Types.Verification where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias
import {-# SOURCE #-} MockServer.Types.ExpectationId
import {-# SOURCE #-} MockServer.Types.RequestDefinition
import {-# SOURCE #-} MockServer.Types.VerificationTimes

-- | Defines the object schema located at @components.schemas.Verification@ in the specification.
-- 
-- verification
data Verification = Verification {
  -- | expectationId
  verificationExpectationId :: (GHC.Maybe.Maybe ExpectationId)
  -- | httpRequest
  , verificationHttpRequest :: (GHC.Maybe.Maybe RequestDefinition)
  -- | maximumNumberOfRequestToReturnInVerificationFailure
  , verificationMaximumNumberOfRequestToReturnInVerificationFailure :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | times: number of request to verify
  , verificationTimes :: (GHC.Maybe.Maybe VerificationTimes)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Verification
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("expectationId" Data.Aeson.Types.ToJSON..=)) (verificationExpectationId obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpRequest" Data.Aeson.Types.ToJSON..=)) (verificationHttpRequest obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("maximumNumberOfRequestToReturnInVerificationFailure" Data.Aeson.Types.ToJSON..=)) (verificationMaximumNumberOfRequestToReturnInVerificationFailure obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("times" Data.Aeson.Types.ToJSON..=)) (verificationTimes obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("expectationId" Data.Aeson.Types.ToJSON..=)) (verificationExpectationId obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("httpRequest" Data.Aeson.Types.ToJSON..=)) (verificationHttpRequest obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("maximumNumberOfRequestToReturnInVerificationFailure" Data.Aeson.Types.ToJSON..=)) (verificationMaximumNumberOfRequestToReturnInVerificationFailure obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("times" Data.Aeson.Types.ToJSON..=)) (verificationTimes obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON Verification
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Verification" (\obj -> (((GHC.Base.pure Verification GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "expectationId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "httpRequest")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "maximumNumberOfRequestToReturnInVerificationFailure")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "times"))
-- | Create a new 'Verification' with all required fields.
mkVerification :: Verification
mkVerification = Verification{verificationExpectationId = GHC.Maybe.Nothing,
                              verificationHttpRequest = GHC.Maybe.Nothing,
                              verificationMaximumNumberOfRequestToReturnInVerificationFailure = GHC.Maybe.Nothing,
                              verificationTimes = GHC.Maybe.Nothing}
