-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema XmlResponseBody
module MockServer.Types.XmlResponseBody where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.XmlResponseBody@ in the specification.
-- 
-- xml response body
data XmlResponseBody = XmlResponseBody {
  -- | contentType
  xmlResponseBodyContentType :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | not
  , xmlResponseBodyNot :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | type
  , xmlResponseBodyType :: (GHC.Maybe.Maybe XmlResponseBodyType)
  -- | xml
  , xmlResponseBodyXml :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON XmlResponseBody
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("contentType" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyContentType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("xml" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyXml obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("contentType" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyContentType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("xml" Data.Aeson.Types.ToJSON..=)) (xmlResponseBodyXml obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON XmlResponseBody
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "XmlResponseBody" (\obj -> (((GHC.Base.pure XmlResponseBody GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "contentType")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "not")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "xml"))
-- | Create a new 'XmlResponseBody' with all required fields.
mkXmlResponseBody :: XmlResponseBody
mkXmlResponseBody = XmlResponseBody{xmlResponseBodyContentType = GHC.Maybe.Nothing,
                                    xmlResponseBodyNot = GHC.Maybe.Nothing,
                                    xmlResponseBodyType = GHC.Maybe.Nothing,
                                    xmlResponseBodyXml = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.XmlResponseBody.properties.type@ in the specification.
-- 
-- 
data XmlResponseBodyType =
   XmlResponseBodyTypeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | XmlResponseBodyTypeTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | XmlResponseBodyTypeEnumXML -- ^ Represents the JSON value @"XML"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON XmlResponseBodyType
    where toJSON (XmlResponseBodyTypeOther val) = val
          toJSON (XmlResponseBodyTypeTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (XmlResponseBodyTypeEnumXML) = "XML"
instance Data.Aeson.Types.FromJSON.FromJSON XmlResponseBodyType
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "XML" -> XmlResponseBodyTypeEnumXML
                                            | GHC.Base.otherwise -> XmlResponseBodyTypeOther val)
