-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema XpathBodyMatcher
module MockServer.Types.XpathBodyMatcher where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified MockServer.Common
import MockServer.TypeAlias

-- | Defines the object schema located at @components.schemas.XpathBodyMatcher@ in the specification.
-- 
-- xpath body matcher
data XpathBodyMatcher = XpathBodyMatcher {
  -- | not
  xpathBodyMatcherNot :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | type
  , xpathBodyMatcherType :: (GHC.Maybe.Maybe XpathBodyMatcherType)
  -- | xpath
  , xpathBodyMatcherXpath :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON XpathBodyMatcher
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (xpathBodyMatcherNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (xpathBodyMatcherType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("xpath" Data.Aeson.Types.ToJSON..=)) (xpathBodyMatcherXpath obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("not" Data.Aeson.Types.ToJSON..=)) (xpathBodyMatcherNot obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (xpathBodyMatcherType obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("xpath" Data.Aeson.Types.ToJSON..=)) (xpathBodyMatcherXpath obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON XpathBodyMatcher
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "XpathBodyMatcher" (\obj -> ((GHC.Base.pure XpathBodyMatcher GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "not")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "xpath"))
-- | Create a new 'XpathBodyMatcher' with all required fields.
mkXpathBodyMatcher :: XpathBodyMatcher
mkXpathBodyMatcher = XpathBodyMatcher{xpathBodyMatcherNot = GHC.Maybe.Nothing,
                                      xpathBodyMatcherType = GHC.Maybe.Nothing,
                                      xpathBodyMatcherXpath = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.XpathBodyMatcher.properties.type@ in the specification.
-- 
-- 
data XpathBodyMatcherType =
   XpathBodyMatcherTypeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | XpathBodyMatcherTypeTyped Data.Aeson.Types.Internal.Object -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | XpathBodyMatcherTypeEnumXPATH -- ^ Represents the JSON value @"XPATH"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON XpathBodyMatcherType
    where toJSON (XpathBodyMatcherTypeOther val) = val
          toJSON (XpathBodyMatcherTypeTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (XpathBodyMatcherTypeEnumXPATH) = "XPATH"
instance Data.Aeson.Types.FromJSON.FromJSON XpathBodyMatcherType
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "XPATH" -> XpathBodyMatcherTypeEnumXPATH
                                            | GHC.Base.otherwise -> XpathBodyMatcherTypeOther val)
