name: Haskell-CI
on: [push]
jobs:
  linux:
    name: GHC-${{ matrix.ghc-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version:
          - 9.0.2
          - 9.2.5
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ matrix.ghc-version }}
          stack-version: 'latest'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            ./.stack-work
          key: ${{ matrix.ghc-version }}
      - run: stack --stack-yaml ghc-${{ matrix.ghc-version }}.yaml --install-ghc test --fast --haddock
